apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo1
  name: demo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo1
    spec:
      containers:
      - image: BankingApplication:209
        name: demo1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: demo1
